import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="p-7 bg-zinc-800 ">
                    <a href="" className="logo">
                        GiftPal
                    </a>
                </header>
                <main className="p-8">{children}</main>
            </body>
        </html>
    );
}
